src/main/webapp/definitions/alfresco-core.yaml

- In common with other *Entry types
- Added MinimalNode type which contains the actual node props previously
on NodeMinimalEntry
Ref RA-969

NodeMinimalEntry should have a single property 'entry'

---

src/main/webapp/definitions/alfresco-core.yaml

Note this is an optional property, only present when include=paths is specified on
request. However without this property definition this optional information is not visible via a generated API client.

Add path element to returned properties for nodes

---

src/main/webapp/definitions/alfresco-core.yaml

REPO-1600 spec change for zones filtering. Also fixed for isRoot filtering and include=parentIds,zones

REPO-1600/REPO-1583: zones and isRoot filtering and include param.

---

src/main/webapp/definitions/alfresco-core.yaml

Added to get /favorites, post /favorites and get /favorites/<id>, an include parameter object to contain path.

APPSREPO-188: Added include=path parameter to favorites api

---

src/main/webapp/definitions/alfresco-core.yaml

Updated the OpenAPI spec. to include the extra info on path elements:
* nodeType (short form, e.g. cm:folder)
* aspectNames (list of short form aspect names, e.g. st:siteContainer)

REPO-2983: include extra info for node path elements

---

src/main/webapp/definitions/alfresco-core.yaml

This new REST API is used to support probes in K8s

REPO-3504: repo probe

---

src/main/webapp/definitions/alfresco-core.yaml

* update createNode documentation with optionally creating of permission. Text was taken and adjusted from updateNode area.

REPO-3950 Permissions on Create Node

---

src/main/webapp/definitions/alfresco-core.yaml

As per [BUILDER-131](https://issues.alfresco.com/jira/browse/BUILDER-131), Currently the return type of the Get binary content REST APIs generated by swagger-codegen is *Void*, which means  we can't get the response as a binary/file in our Java clients.
This PR will fix the issue.

BUILDER-131: Fixed Get Binary Content API Defs.

---

src/main/webapp/definitions/alfresco-core.yaml

Without the fix, Swagger will generate an Integer rather than a Long object, which causes an exception for a large file upload.

BUILDER-170: Fixed contentInfo sizeInBytes property.

---

src/main/webapp/definitions/alfresco-search-sql.yaml

Add the missing commas noticed while checking the timezone.
Note that the timezone is currently not supported - see SEARCH-2145.

SEARCH-2140 Fix SQL search example.

---

src/main/webapp/definitions/alfresco-core.yaml

Incrementally update Versions API with four new endpoints for version-specific renditions:
- GET /nodes/{nodeId}/versions/{versionId}/renditions - List renditions for a version
- POST /nodes/{nodeId}/versions/{versionId}/renditions - Create rendition for a version
- GET /nodes/{nodeId}/versions/{versionId}/renditions/{renditionId} - Get rendition information for a version
- GET /nodes/{nodeId}/versions/{versionId}/renditions/{renditionId}/content - Get rendition content for a version

ACS-197 / ACS-238 : Add Version Renditions updates to Core OpenAPI Spec

---

src/main/webapp/definitions/alfresco-core.yaml

The API  /nodes/{nodeId} should return the current node type ( different from the content model type definition) of the dictionary in the repository. The purpose is to give all the information we need when we are using or exploring a node (properties, constrains, etc.) including inherited  properties from parents or aspects.
All the information should be retuned without the need for additional API calls.

[REPO-5169] API Node Definitions

---

src/main/webapp/definitions/alfresco-core.yaml

The API /nodes/{nodeId} will return the Definition of the node when tha query parameter ?include=definition is added to the request. 
Thia functionality was discussed and reviewed in  PR #90 and PR #93 but it was reverted from master because it has to be part of ACS 7 and not ACS 6.2.2.

[REPO-5169] Added Definition to node API

---

src/main/webapp/definitions/alfresco-core.yaml

REST APIs that send email to use an optional client name. The client name is used to lookup the custom email template and its related assets based on the registered configuration.
https://alfresco.atlassian.net/browse/ACS-777

[ACS-777] Email notification for digital workspace

---

src/main/webapp/definitions/alfresco-core.yaml

Add to versionedEnabled flag for `POST ​/nodes​/{nodeId}​/children` endpoint spec.

MNT-22036 : Add versionedEnabled flag

---

src/main/webapp/definitions/alfresco-core.yaml

Pretty self-explanatory, path information is available but undocumented.

Add missing path information present on SharedLinks

---

src/main/webapp/definitions/alfresco-core.yaml

The fields are documented as required but ACS doesn't return them in certain situations.
**mimeTypeName** isn't always returned by search while **sizeInBytes** isn't returned by rendition calls.

Remove incorrectly documented ContentInfo required fields

---

src/main/webapp/definitions/alfresco-core.yaml

While testing on one of the trials environment we've noticed that **properties** field on **person** returns a dictionary with values being arrays of attributes which is different to the definition and ends up raising a parsing exception with bindings that include type information.
As such this PR aims to remove the value type for the properties object on person introduced by https://github.com/Alfresco/rest-api-explorer/pull/99

Properties field on person should accept structured data

---

src/main/webapp/definitions/alfresco-search.yaml
src/main/webapp/index.html

As in https://stackoverflow.com/a/65782841/1654265
Removed the warnings printed by Swagger UI, 
reduced the notice about them and moved it at the end of the description,
added an example for the Pivot API to prevent the `null` problem.
The branch won't be deleted, it will be used to migrate the project to Travis on a later PR.

Hidden warnings, added pivot example, moved error notice

---

src/main/webapp/definitions/alfresco-core.yaml

```yaml
'412':
description: |
Content is archived and is inaccessible
```
Added the above error code to the following "get (download) content" endpoints:
- GET /nodes/`{nodeId}`/content
- GET /nodes/`{nodeId}`/renditions/`{renditionId}`/content
- GET /nodes/`{nodeId}`/versions/`{versionId}`/content
- GET /nodes/`{nodeId}`/versions/`{versionId}`/renditions/`{renditionId}`/content
- GET /deleted-nodes/`{nodeId}`/content
- GET /deleted-nodes/`{nodeId}`/renditions/`{renditionId}`/content
- GET /shared-links/`{sharedId}`/content
- GET /shared-links/`{sharedId}`/renditions/`{renditionId}`/content
and also the following "request direct access url" endpoints:
- POST /nodes/`{nodeId}`/request-direct-access-url
- POST /nodes/`{nodeId}`/renditions/`{renditionId}`/request-direct-access-url
- POST …

ACS-2222 Add 412 error for Archived Content

---

src/main/webapp/definitions/alfresco-core.yaml

This PR introduces storage properties related endpoint definitions.
It includes changes provided in [PR#141](https://github.com/Alfresco/rest-api-explorer/pull/141) which will be closed.
- Added a new GET endpoint definition to get storage properties `/nodes/{nodeId}/storage-info/{contentPropName}`
- Added 2 new POST endpoint definitions for archive (`/nodes/{nodeId}/storage-info/{contentPropName}/archive`) and archive-restore (`/nodes/{nodeId}/storage-info/{contentPropName}/archive-restore`) operations 
- Added `contentPropNameParam` path parameter definiotn
- Added `ContentStorageInfo` model object definition to handle StorageProps exposure in response
- Added request body object definitions for POST endpoints (`RestoreArchivedContentRequest`, `ArchiveContentRequest`)
- Added a new …

ACS-2151: Initial definitions for get StorageProps endpoint.

---

src/main/webapp/definitions/alfresco-core.yaml

Add storage properties endpoints for version content (in addition to iive content):
- GET /nodes/{nodeId}/versions/{versionId}/storage-info/{contentPropQName}
- POST /nodes/{nodeId}/versions/{versionId}/storage-info/{contentPropQName}/archive
- POST /nodes/{nodeId}/versions/{versionId}/storage-info/{contentPropQName}/archive-restore
Also:
- tweaked some of the existing endpoints (for consistency, eg. added 404 error code)
Relates to: https://github.com/Alfresco/alfresco-community-repo/pull/863

ACS-2391: StorageObjectProps - add version content specific endpoints

---

src/main/webapp/definitions/alfresco-core.yaml

- fix blatant typo (copy & paste of op ids) that caused the API Explorer (swagger) to open the wrong op
- see ACS-2391

ACS-2461:  StorageObjectProps - add version content specific endpoints

---

src/main/webapp/definitions/alfresco-core.yaml

According to the current state of our code it is not possible to overwrite an existing file which is not versional via POST request using "/nodes/{nodeId}/children" endpoint both for multipart and json upload.  (see MMT-22462)

Updated a description of the restapi explorer about overwriting an existing file which is not versionable

---

src/main/webapp/definitions/alfresco-core.yaml

-Add missing parenthesis across multiple filter descriptions
-Remove one extra parenthesis found looking for missing parenthesis

[MNT-22106] Missing parenthesis in filter description

---

src/main/webapp/definitions/alfresco-core.yaml

Initial spec for Rules CRUD. More PRs to follow, eg. to add link/unlink rulesets etc.
Also some small changes to the GET rules API, the largest being the introduction
of a new type for action definitions (one that doesn't include a target node id).

ACS-3183 POST rules, GET, PUT and DELETE rule API definition.

---

src/main/webapp/definitions/alfresco-core.yaml

Changed path parameter name (from `actionConstraintName` to `parameterConstraintName`) to be the same as `action-definitions` endpoint returns in reponse.
Added missing (`parameterConstraintName`) in response object for `action-definitions` endpoint.
Removing `isNode` from `ActionConstraintData` object.

ACS-3572 Action Constraints endpoint

---

src/main/webapp/definitions/alfresco-core.yaml

I am not sure if the path `/category/{categoryId}` was meant here or that was only sort of TYPO but I believe that if we want to be consistent with all other V1 endpoints, we should make this change (although we don't have GET all categories endpoint designed or planned yet).

ACS-4022: Fixing the path for category related endpoints.

---

src/main/webapp/definitions/alfresco-core.yaml

https://alfresco.atlassian.net/browse/ACS-4034
Small PR adjusting specification to our REST framework (for POST: same field names in input and output).

ACS-4034: Assign a piece of content to a category

---

src/main/webapp/definitions/alfresco-core.yaml

https://alfresco.atlassian.net/browse/ACS-4023
This PR is about updating field `name` to `tag` in where query.

Update GET /tags to support getting tags by name

---

src/main/webapp/definitions/alfresco-core.yaml

https://alfresco.atlassian.net/browse/ACS-4966
This PR is about adding `path` param to Categories API.

ACS-4966 Add path to Category model

---

src/main/webapp/definitions/alfresco-core.yaml
src/main/webapp/definitions/alfresco-search.yaml

These small additions have been requested by MobileApps team to let them lower down number of API calls when performing some sort of bulk operations.

ACS-5624: Search and Favorites API enhancements.

---

src/main/webapp/definitions/alfresco-core.yaml

The support for this already exists, but it was missed when creating the API explorer definitions.

ACS-5829 Add pagination parameters to targets and sources.

---

src/main/webapp/definitions/alfresco-core.yaml

https://alfresco.atlassian.net/browse/MNT-24127

[MNT-24127] Added Endpoint to calculate the size of a folder

---

src/main/webapp/definitions/alfresco-core.yaml

Reverts the changes for Calculating the Node Size.

Revert "[MNT-24127] Added Endpoint to calculate the size of a folder

---

src/main/webapp/definitions/alfresco-core.yaml

https://hyland.atlassian.net/browse/MNT-24127

[MNT-24127] Added Endpoint To Calculate Folder Size

---

src/main/webapp/definitions/alfresco-core.yaml

Accidentally merged PR i.e. 
https://github.com/Alfresco/rest-api-explorer/pull/213/
So, reverting the PR.

Revert "[MNT-24127] Added Endpoint To Calculate Folder Size"

---

src/main/webapp/definitions/alfresco-core.yaml

https://hyland.atlassian.net/browse/MNT-24127

[MNT-24127] Added Endpoint to Calculate the Folder Size.
