Alfresco/rest-api-explorer

src/main/webapp/definitions/alfresco-core.yaml
Reverts Alfresco/rest-api-explorer#3
=> Revert "Add path element to returned properties for nodes"

src/main/webapp/definitions/alfresco-core.yaml
=> Add optional path property to NodeMinimal

src/main/webapp/definitions/alfresco-discovery.yaml
- updated API spec to mention the 501 status code if the service is disabled
=> REPO-1415: Allow Discovery to be disabled - update API spec (see A/C)

src/main/webapp/definitions/alfresco-core.yaml
- updated implementation notes for orderBy limit
=> REPO-1300: Retrieve list of groups

src/main/webapp/definitions/alfresco-core.yaml
- updated implementation notes for orderBy limit
=> REPO-1302: Retrieve list of group members

src/main/webapp/definitions/alfresco-auth.yaml
Spec updated to reflect actual implementation.
=>     REPO-1763  OpenAPI spec states that a 404 should be returned for an expired ticket but doesn't

src/main/webapp/definitions/alfresco-core.yaml
Could you please review the new OpenAPI spec for the download as a zip API.
Thanks
=> APPSREPO-34 : Added specs for the /downloads API

src/main/webapp/definitions/alfresco-core.yaml
- updated  by adding specifications details about 404 response code
=> REPO-1304: Create a group

src/main/webapp/definitions/alfresco-core.yaml
- added specifications details about 409 response code (Trying to modify a fixed authority)
=> REPO-1305: Delete a group

src/main/webapp/definitions/alfresco-core.yaml
- updated Api Specs with new error codes
=> REPO-1878: Prevent manipulation of GROUP_EVERYONE in all endpoints

src/main/webapp/definitions/alfresco-core.yaml
@gavincornwell please review.
Thanks
=> APPSREPO-152: Added Password Reset API spec.

src/main/webapp/css/alfresco.css, src/main/webapp/index.html
Alongside with addition of a new input box I had to change the styling to be able to fit everything in the header.
=> REPO-2914 Allow changing of hostname in requests

src/main/webapp/definitions/alfresco-core.yaml
https://issues.alfresco.com/jira/browse/REPO-2828
Added additional fields to quickshare link info, plus added allowable operations info on the target file.
=> REPO-2828 quickshare: additional info

src/main/webapp/definitions/alfresco-core.yaml
=> REPO-1206: actions

src/main/webapp/definitions/alfresco-core.yaml
Updating the Api-Explorer with range header endpoint
=> REPO-3271: Range Request Documentation

src/main/webapp/definitions/alfresco-core.yaml
- updated approve and reject site membership requests to allow 403 exception in some use cases
=> REPO-2093: Allow site managers to accept and reject site invitations

src/main/webapp/definitions/alfresco-core.yaml
- fix wrong maps, add missing params and remove unnecessary ones
=> BUILDER-73: Fix issues in generated models

src/main/webapp/definitions/alfresco-core.yaml
=> Fix spelling minor issue

src/main/webapp/definitions/alfresco-core.yaml
- add orderBy parameter to GET /people/{personId}/favorites api
=> REPO-3630/MNT-19696: REST API add order by parameter option to GET favorites

src/main/webapp/definitions/alfresco-sync-service.yaml, src/main/webapp/index.html, src/test/java/org/alfresco/api/YamlToJson.java, src/test/java/org/alfresco/test/APIExplorerIntegrationTest.java
Sync Service REST APIs Swagger Definitions
=> APPSREPO-724: Sync Service Rest API Swagger Definitions

src/main/webapp/definitions/alfresco-sync-service.yaml
Fixed yaml file for failing build.
=> APPSREPO-724: Fixed yaml file for failing build

src/main/webapp/definitions/alfresco-core.yaml
- add min/max audit entry id params to audit application
=> REPO-4950: Retrieve min,max audit record ids for Audit app and add script

src/main/webapp/definitions/alfresco-sync-service.yaml
Reverts Alfresco/rest-api-explorer#81
=> Revert "APPSREPO-724: Fixed yaml file for failing build"

src/main/webapp/definitions/alfresco-core.yaml
Reverts Alfresco/rest-api-explorer#93 This will be part of ACS7 and not ACS 6.2.2
=> Revert "Feature/repo 5169 api compiled models"

src/main/webapp/definitions/alfresco-core.yaml
Reverts Alfresco/rest-api-explorer#90 This will be part of ACS7 and not ACS 6.2.2
=> Revert "[REPO-5169] API Node Definitions"

src/main/webapp/definitions/alfresco-core.yaml
=> ACS-306: ACS Repository: V1 Rest API for content direct access urls

src/main/webapp/definitions/alfresco-core.yaml
https://issues.alfresco.com/jira/browse/REPO-5184
=> [REPO-5184] REST API: Add isMemberOfGroup property to sites/members

run.sh, src/main/webapp/definitions/alfresco-core.yaml
https://issues.alfresco.com/jira/browse/REPO-5185
=> [REPO-5185] REST API: Add endpoint to expose the groups of a site

src/main/webapp/definitions/alfresco-core.yaml
Related to [PR #706](https://github.com/Alfresco/alfresco-remote-api/pull/706)
=> [REPO-5239] add filter by displayName to /groups API documentation

src/main/webapp/definitions/alfresco-core.yaml
(cherry picked from commit 6df1377406f2d149af4d308035ff24b0b074bba8)
=> MNT-21936 : Add omitTotalItems parameter. #102

src/main/webapp/definitions/alfresco-core.yaml
MNT-22036 : Add versionedEnabled flag
(cherry picked from commit 69b450e88dba6190b561789f62cfeb19d1d34713)
=> MNT-22036 : Add versionedEnabled flag

src/main/webapp/definitions/alfresco-core.yaml, src/main/webapp/definitions/alfresco-model.yaml, src/main/webapp/index.html, src/test/java/org/alfresco/api/YamlToJson.java, src/test/java/org/alfresco/test/APIExplorerIntegrationTest.java
https://alfresco.atlassian.net/browse/REPO-5440
https://alfresco.atlassian.net/browse/REPO-5552
=> Aspect and Type api implementation

src/main/webapp/definitions/alfresco-model.yaml
show model in the aspect/type api
=> [REPO-5552] show model in the aspect/type api

src/main/webapp/definitions/alfresco-model.yaml
Following capability added to aspect/type api
* include properties
* include associations
* INCLUDESUBTYPES
* INCLUDESUBASPECTS
* typo fixed
=>  [REPO-5552] more filtering capablities for aspect/type api

src/main/webapp/definitions/alfresco-core.yaml
=> [ACS-1715]Deprecate reset-password and request-password-reset API

src/main/webapp/definitions/alfresco-core.yaml
- consistent with GET .../content APIs (attachment param)
=> PRODESC-5780: ACS Repo DAU APIs to also use non-attach allow list

src/main/webapp/definitions/alfresco-core.yaml
Added new endpoints:
```
DELETE /nodes/{nodeId}/renditions/{renditionId}
DELETE /nodes/{nodeId}/versions/{versionId}/renditions/{renditionId}
```
=> MNT-22696 Replace renditions via REST API

src/main/webapp/definitions/alfresco-core.yaml
* MNT-22696 Replace renditions via REST API
* MNT-22696 Corrections from PR review
* MNT-22696 Corrections from PR review
(cherry picked from commit c17dcb8312cd5435752d4fed093cd4cd77c14554)
=> MNT-22696 Replace renditions via REST API (#145)

.travis.yml
7.2.0-A4 release. May be worth to mention: https://alfresco.atlassian.net/browse/ACS-2504
=> MNT-22462 [release] 7.2.0-A4

src/main/webapp/definitions/alfresco-core.yaml
https://alfresco.atlassian.net/browse/ACS-3194
Review alongside: https://github.com/Alfresco/rest-api-explorer/pull/161
=> [ACS-3194] API for linked rules

src/main/webapp/definitions/alfresco-core.yaml
https://alfresco.atlassian.net/browse/ACS-3525
=> ACS-3525: API for manual triggering rules on a folder

src/main/webapp/definitions/alfresco-core.yaml
https://alfresco.atlassian.net/browse/ACS-4362
=> ACS-4362: Fix returned HTTP error status for invalid note type

pom.xml
https://alfresco.atlassian.net/browse/ACS-6444
=> updated swagger-ui version to 4.1.3

src/main/webapp/definitions/alfresco-core.yaml
Reverted Swagger changes for MNT-24127
=> Reverted Swagger changes for MNT-24127

src/main/webapp/definitions/alfresco-core.yaml, src/main/webapp/definitions/alfresco-search.yaml
https://hyland.atlassian.net/browse/APPS-3106
Add Alfresco Java SDK Docs as part of nexus repository artifacts
=> [APPS-3106] Removed special characters from yaml files
